SecurityConfig 권한별 Url 접속 에러 수정
Team-Ampersand/Dotori-server pull request #133
Opened 2021-09-20 08:51 UTC by KyungJunNoh

### 제가 한일은요!
- 일치하는 권한으로 url을 접속했을때 안되던 에러를 수정했습니다.

> 현재 더 확인해야할게 있지만 Exception메세지가 불특정하게 나오고 -9999 에러, 에러가 일치하지 않으므로 작업하기가 힘듭니다. 우선 @TeMlN 님의 에러가 빨리 고쳐져야지 제 기능도 완벽히 완성할 수 있을것같습니다.

![2021-09-20_17-47-54](https://user-images.githubusercontent.com/68670670/133977081-96e3af77-a53d-4c25-ad8c-670ca30b3d54.png)

2021-09-20 08:54 UTC, qoxogus requested changes
현재는 설정해놓은 점들을 모두 주석처리 해주시고 (제약조건, 전역예외처리 메세지 등 테스트 되지 않은 것 들이 있음)
다른 작업들이 끝나면 주석을 해제하는 방법을 사용해야할 것 같습니다.

2021-09-20 08:54 UTC, qoxogus commented on src/main/java/com/server/Dotori/security/SecurityConfig.java
> +                .antMatchers("/v1/member/logout").permitAll()
로그아웃과 회원탈퇴 기능은 로그인 되어있을 때만 접근이 허용되게 해야 합니다.

2021-09-20 08:59 UTC, qoxogus commented
>  /v1/admin/board를 COUNCILLOR 으로 접근했을때 뜨는 메세지 (이 에러메세지가 현재 권한이 맞지 않다고 떠야합니다.)

### 이 부분에 대해 말씀드리겠습니다. 
제 생각은 
**권한별로 필요하지 않은 컨트롤러들은 작성하지 않았기 때문에 API가 존재하지 않다고 뜨는 것 같기도 합니다.**

또 다른 생각은 
**Exception Handler가 Security 설정 중 권한별 url접속을 했을 때 던지는 예외보다 Exception Handler가 더 먼저 동작**하는 것 같기도 합니다.

### **물론 어디까지나 제 생각일 뿐이니 참고만 해주세요.**

2021-09-20 09:01 UTC, KyungJunNoh commented
> > /v1/admin/board를 COUNCILLOR 으로 접근했을때 뜨는 메세지 (이 에러메세지가 현재 권한이 맞지 않다고 떠야합니다.)
> 
> ### 이 부분에 대해 말씀드리겠습니다.
> 제 생각은
> **권한별로 필요하지 않은 컨트롤러들은 작성하지 않았기 때문에 API가 존재하지 않다고 뜨는 것 같기도 합니다.**
> 
> 또 다른 생각은
> **Exception Handler가 Security 설정 중 권한별 url접속을 했을 때 던지는 예외보다 Exception Handler가 더 먼저 동작**하는 것 같기도 합니다.
> 
> ### **물론 어디까지나 제 생각일 뿐이니 참고만 해주세요.**

무슨말인지 알것같네요 그러면 이부분은 Exception 작업을 모두 마치고 다시 확인해보도록 하겠습니다

2021-09-20 09:12 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/security/SecurityConfig.java
> +//                .antMatchers("/v1/member/delete").authenticated()
변경했습니다 확인해주세요

2021-09-20 09:14 UTC, qoxogus approved these changes
확인했습니다.

2021-09-22 06:18 UTC, TeMlN approved these changes
확인 했습니당

2021-09-22 06:18 UTC, merged

2021-09-22 06:19 UTC, TeMlN commented
알 수 없는 에러 문제 지금 해결하도록 하겠습니다