Feature/exception message
Team-Ampersand/Dotori-server pull request #144
Opened 2021-10-04 07:28 UTC by TeMlN

* 한 일
  i18n 메세지를 변경하였습니다~ en 경우는 그대로 놔두어도 될 것 같다고 판단해서 변경하지 않았습니다

2021-10-04 07:47 UTC, qoxogus requested changes
누락된 부분이 있는 것 같아요
slack `server-issue` 확인바랍니다.

2021-10-04 22:56 UTC, qoxogus approved these changes
확인했습니다.

2021-10-05 06:52 UTC, KyungJunNoh approved these changes
확인했습니다.

2021-10-05 07:14 UTC, qoxogus requested changes
수고하셨습니다 ~ 
코멘트 확인 바랍니다 ~

2021-10-05 07:14 UTC, qoxogus commented on src/main/java/com/server/Dotori/exception/selfstudy/SelfStudyExceptionHandler.java
> +    @ResponseStatus(HttpStatus.OK)
`200, OK`가 아닌 `202, ACCEPT`로 변경되야 할 것 같아요
다른 exception response http status들도 확인 바랍니다.

2021-10-05 07:36 UTC, merged