Redis 레거시 청산 [1]
Team-Ampersand/Dotori-server pull request #190
Opened 2021-12-16 13:27 UTC by KyungJunNoh

### 제가 한일은요!
- 성능의 이슈가 있어 Redis를 삭제하고 DB로 마이그레이션 하여 Redis 레거시를 청산하였습니다.

청산 해야되는 목록은
- 로그인, 로그아웃
- refreshToken
- 이메일   

이 있었지만 하도 겹쳐지는 부분이 많다보니 한번에 작업하였습니다..
코드리뷰에 어려움이 있을테니.. 잘 부탁드립니다..ㅎ

레거시 청산이 아직 남아있어서 1,2로 쪼개서 다음 PR에 추가로 올리도록 하겠습니다.

2021-12-16 23:19 UTC, qoxogus requested changes
확인했습니다. 
코멘트 확인해주세요

2021-12-16 23:19 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
>          } else {
인증번호 사용 시 인증번호 사용 여부 expired를 true로 변경해주는 코드가 없어요 
그리고 인증키를 받았을 때 인증번호를 사용했는지 검증이 안되었어요

2021-12-16 23:19 UTC, qoxogus commented on src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
> +        assertThat(key).isEqualTo(emailCertificateRepository.findByKey(key).getKey());
메일 실제로 보내지는 부분이라 테스트 `@Disable`처리 되어있습니다.
`@Disable`을 해제하고 테스트한 뒤 다시 `@Disable`추가 후 PR보내신거 맞으신가요 ?

2021-12-16 23:22 UTC, KyungJunNoh commented on src/test/java/com/server/Dotori/model/member/service/email/EmailServiceTest.java
> +        assertThat(key).isEqualTo(emailCertificateRepository.findByKey(key).getKey());
확인 후 다시 보내도록 하겠습니다

2021-12-16 23:37 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
>          } else {
**인증키를 받았을 때 인증번호를 사용했는지 검증** 부분이 **expired 가 true 인지 false 인지 검증이 되어야 한다는 것**같은데
```emailCertificateRepository.findByKey(key).getExpiredTime().isAfter(LocalDateTime.now())```
여기서 만료가 되었는지 안되었는지 체크하고

키가 일치하다면 아래사진처럼 해당 데이터를 삭제하기때문에 추가 안했던것입니다.
<img width="442" alt="2021-12-17_08-29-57" src="https://user-images.githubusercontent.com/68670670/146464205-8ce4c692-4fd6-436a-b182-365f849321db.png">

그리고 다음 PR에 만료일이 지난 인증키는 삭제 하는 코드를 넣을 예정입니다.

2021-12-16 23:40 UTC, KyungJunNoh commented
@Disabled 된 테스트 성공하여 수정사항 없이 올렸습니다

2021-12-16 23:46 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
>          } else {
제 말은 인증키를 사용한 적이 있는지 검증해야한다는 말이였습니다.

@KyungJunNoh 님 말대로라면 인증번호 사용여부, 그에대한 검증을 넣지 않고 유효기간만 검증하겠다는 말씀이신가요 ?

그렇게 된다면 expired 컬럼은 필요없게되니 삭제되도 좋을 것 같아요

2021-12-16 23:49 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
>          } else {
맞습니다. 제가 코딩전에 생각한 로직에 컬럼이 필요없다고 생각했는데 말을 못했네요
@TeMlN 한테 말해서 컬럼 수정요청 하겠습니다

2021-12-17 00:04 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
>          } else {
인증시간이 초과되었을 때, 데이터를 삭제하는 코드가 필요할 것 같아요

2021-12-17 00:09 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/member/service/email/EmailServiceImpl.java
> +        }
서버에서는 3분안에 인증번호 재 요청이 들어와도 막을 방법이 없을 것 같네요 (굉장히 복잡할 듯)
프론트에서 블락처리 한다고 했으니 서버에는 그냥 놔둬야할 듯 합니다.. 
(블락 한 30초만 해도 될 것 같아요, 이메일을 잘못입력했을 때 인증번호 재요청을 할 수도 있고
이메일을 몇번 더 보내도 딱히 문제가 될 것 같지 않아요)

![스크린샷 2021-12-17 오전 9 06 12](https://user-images.githubusercontent.com/69895394/146466968-475fd848-8ed0-4fe5-8b4a-64b72a877f90.png)

email에 unique 제약조건도 걸려있지 않으니 그냥 나두면 될 듯 합니다!

전에 이 얘기가 나와서 리뷰 달아봤습니다.

2021-12-17 01:08 UTC, TeMlN reviewed
comment 확인해주세요~ 수고하셨어요

2021-12-17 01:08 UTC, TeMlN commented on src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
> +                .member(null)
혹시 이건 회원가입 할때 사용되는 이메일 인증에만 사용하는 dto인가요?? 그게 아니라면 tonEntity에서 null로 지정해주는게 아니라 member를 받아야 할거같아요(기본값을 null로 설정하거나 해야할거 같아요)

2021-12-17 01:12 UTC, TeMlN commented on src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
> +                .member(null)
혹은 로그인 / 비로그인 했을때를 기준으로 DTO를 두개 작성해도 될것 같네요 `SignupEmailCertificateDto` 나 `FindPwEmailCertificateDto` 이런식으로요~

2021-12-17 01:17 UTC, qoxogus commented
다음부턴 한 기능씩에만 집중해서 PR 날려주세요

2021-12-17 01:19 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
> +                .member(null)
아규먼트 값으로 null을 전달하여 toEntity 의 파라미터로 받아서 null로 지정해줘야 한다는 말인가요?

2021-12-17 01:19 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
> +                .member(null)
이 DTO는 회원가입할때 사용되는 DTO 입니다.
다른 이메일이 필요한 로직인 ( 로그인 했을때 이메일인증을 필요할때 DTO 들은 나중에 처리할때 고려해보도록 하겠습니다.)
무슨말인지는 알것같네요.
작업영역이 넓다보니 PR분할이 제대로 되지 못하여 제의도가 잘 전달되지 못한것같습니다 ㅠ

2021-12-17 01:19 UTC, KyungJunNoh commented
> 다음부턴 한 기능씩에만 집중해서 PR 날려주세요

작업영역이 넓어지다보니 PR 분할을 고려하지못했네요
유의하겠습니다

2021-12-17 01:25 UTC, merged

2021-12-17 01:26 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/member/dto/EmailCertificateDto.java
> +                .member(null)
저희는 로그인 했을 때 이메일 인증번호를 요청하는 로직이 없습니다.
회원가입, 비밀번호 찾기 이렇게 밖에 없어요
두 기능 모두 로그인 안했을 때 입니다.

비밀번호 찾기 시(이미 가입된 회원이 있기 때문)에 member 연관관계를 맺어주자는 말 
그런 뉘앙스 같은데 맞나요 ?

잘못된 정보를 알고있는 것 같아 알려드립니다.