학생 규정위반을 했을때 기록 하는 기능 추가
Team-Ampersand/Dotori-server pull request #251
Opened 2022-01-16 16:47 UTC by KyungJunNoh

### 제가 한 일은요!!
- 학생이 규정위반을 하여 기록 ( 규정위반을 부여하는 ) 기능을 만들었습니다.

2022-01-17 07:21 UTC, qoxogus requested changes
테스트코드 작성해주세요 !!

2022-01-17 07:56 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/model/rule/service/RuleServiceImpl.java
> +            members.add(member);
잘못썼네요 지우겠습니다

2022-01-17 13:07 UTC, KyungJunNoh commented
### 수정 한 내용
- 잘못써진 members를 지웠습니다.
- 조회 방식을 memberId 에서 stuNum으로 변경했습니다
- 테스트코드를 작성했습니다.

@qoxogus , @TeMlN

2022-01-17 14:43 UTC, qoxogus approved these changes
확인했습니다.

2022-01-18 09:06 UTC, TeMlN approved these changes
확인 했습니다

2022-01-18 09:06 UTC, merged