안마의자 신청 상세로직 추가 및 변경
Team-Ampersand/Dotori-server pull request #270
Opened 2022-01-25 17:08 UTC by TeMlN

안마의자 신청 로직에 필요한 Exception들을 추가하였습니다.
MemberDto 부분에서 EncodePassword -> encodePassword로 카멜 케이스로 변경하였습니다.
안마의자 신청 테스트 케이스를 작성 하였습니다.
controller 네이밍 중복 fix했습니다.

Clean Build, Application Run, Exception 동작 모두 테스트 및 성공하였습니다.

2022-01-25 17:51 UTC, qoxogus requested changes
다른 변경해야 할 점도 많아보여요
다 수정하고 다시 확인하겠습니다 !

2022-01-25 17:51 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
> +        Member currentMember = currentMemberUtil.getCurrentMember();
여기선 currentMember를 사용하는게 아니라 
쿼리문을 이용해서 member 전체를 기준으로 해야해요

member를 전체조회해서 `getMassageExpiredDate().isBefore(LocalDateTime.now()`
이렇게 해결한다면 쿼리문도 굉장히 많이 나갈거에요
querydsl 사용해서 한방쿼리로 해결해야할거에요 !

그리고 안마의자 카운트를 초기화하는 로직도 누락되어있어요 !

2022-01-25 18:30 UTC, TeMlN commented on src/main/java/com/server/Dotori/model/massage/service/MassageServiceImpl.java
> +        Member currentMember = currentMemberUtil.getCurrentMember();
그부분을 놓치고 있었네요 즉시 수정해서 올리겠습니다 카운트 초기화 부분은 다음 신청 취소 부분 pr에서 같이 올리도록 하겠습니다.

2022-01-26 03:38 UTC, qoxogus requested changes
이것만 수정하면 될 것 같아요 !

2022-01-26 03:38 UTC, qoxogus commented on src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
> +    @DisplayName("자정에 안마의자 신청 상태가 변경되는지 확인하는 테스트")
현 테스트는 실제로 변경되는지 확인하는 테스트가 아니에요
그 시간에 일정처럼 예약되어있는지 카운트를 반환해주는 테스트입니다.
DisplayName 변경이 필요해보여요

2022-01-26 09:54 UTC, TeMlN commented on src/test/java/com/server/Dotori/model/member/service/massage/MassageServiceTest.java
> +    @DisplayName("자정에 안마의자 신청 상태가 변경되는지 확인하는 테스트")
확인 후 수정하였습니다

2022-01-26 10:56 UTC, KyungJunNoh approved these changes
확인했습니다.

2022-01-26 10:56 UTC, merged