안마의자 신청 상태, 토탈 카운트 조회 서비스 로직 추가
Team-Ampersand/Dotori-server pull request #275
Opened 2022-01-30 14:53 UTC by TeMlN

사감쌤과 기숙사자치위원회들이 사용할 안마의자 신청 상태와 안마의자 신청 토탈 카운트를 조회하는 서비스 로직을 추가하였습니다

2022-01-30 15:07 UTC, KyungJunNoh approved these changes
확인했습니다.

2022-01-30 19:37 UTC, qoxogus requested changes
코멘트 확인해주세요

2022-01-30 19:37 UTC, qoxogus commented on src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
> +    @GetMapping ("/massage/info")
어드민은 안마의자 신청도 하지않고 상태, 카운트 조회를 하지 않아요,
현 API를 지워야할 것 같아요 (다른 API도 확인해주세요)

또한 학생권한에서 신청 상태와 카운트 조회하는 컨트롤러가 빠진거같아요

클라이언트에서 신청 상태를 보고 서버에 요청을 보낼 수 있는지 등을 판단하기 때문에 
학생 권한에서도 현재 기능에 컨트롤러가 필요해요

2022-02-01 13:58 UTC, TeMlN commented on src/main/java/com/server/Dotori/model/massage/controller/admin/AdminMassageController.java
> +    @GetMapping ("/massage/info")
확인 후 수정 하였습니다!

2022-02-01 13:58 UTC, TeMlN commented
추가로 Controller에서 반환 타입 지정해주었습니다 이거 까지 인지 부탁드립니다!

2022-02-01 14:53 UTC, qoxogus approved these changes
확인했습니다.
API 명세서 작성해주세요.

2022-02-01 14:53 UTC, merged