안마의자 기상음악 사감선생님 의견 반영
Team-Ampersand/Dotori-server pull request #376
Opened 2022-06-02 16:00 UTC by louis7308

* 기상 음악 응답 데이터를 보여줄때 학번도 같이 표시되도록 응답 데이터에 추가했습니다.
* 기존 안마의자는 학번 순서대로 표시되었는데 신청 순서대로 들어 올 수 있게 데이터가 생성된 시간이 빠른 순서대로 오름차순 정렬을 도입했습니다.

2022-06-03 03:28 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
> -        List<MassageStudentsDto> students = memberRepository.findMemberByMassageStatus();
MemberRepositoryCustom 인터페이스의 findMemberByMassageStatus() 는 지웠나요?

2022-06-03 04:19 UTC, qoxogus requested changes
수고하셨습니다. 코멘트 확인해주시고,
수정 완료 후 클라이언트 단 분들께 기상음악 반환값에 학번 추가 됐다고 얘기 부탁드립니다.

2022-06-03 04:46 UTC, KyungJunNoh reviewed
코멘트 확인부탁드려요.

2022-06-03 04:46 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/domain/member/controller/RefreshTokenController.java
> +import javax.servlet.http.Cookie;
사용하지 않는 import는 삭제해주세요

참고로 Intellij 의 설정에서 `Optimize imports on the fly` 옵션을 키면 자동으로 사용하지 않는 import를 제거할 수 있습니다.

<img width="897" alt="2022-06-03_12-29-27" src="https://user-images.githubusercontent.com/68670670/171787764-5c083210-5c37-4890-8eed-421d7483e24f.png">

2022-06-03 05:40 UTC, louis7308 commented on src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
> -        List<MassageStudentsDto> students = memberRepository.findMemberByMassageStatus();
일단 지우진 않고 놔뒀습니다.

2022-06-03 05:48 UTC, qoxogus approved these changes

2022-06-03 06:49 UTC, TeMlN reviewed
수고하셨습니다 !! 코멘트 확인해주세요

2022-06-03 06:49 UTC, TeMlN commented on src/main/java/com/server/Dotori/domain/massage/repository/MassageRepositoryImpl.java
> +    public List<MassageStudentsDto> findByMassageList() {
기존의 안마의자를 신청한 학생들을 불러오는 query가 존재했는데 승원님이 하신대로 `MemberRepositoryImpl`의 `findMemberByMassageStatus` query에서 `orderBy` state만 `createDate.asc` 로만 바꾸면 됐을텐데 새로 생성을 하신 이유가 있나요?

2022-06-03 06:49 UTC, TeMlN commented on src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
> +        return queryFactory.from(member) // User   // user
이 주석의 의미는 뭔가요? 궁금해서 질문남깁니다!

2022-06-03 06:52 UTC, KyungJunNoh commented on src/main/java/com/server/Dotori/domain/massage/service/Impl/MassageServiceImpl.java
> -        List<MassageStudentsDto> students = memberRepository.findMemberByMassageStatus();
findMEmberByMassageStatus() 가 memberRepository에 있는 것보다는 massageRepository에 있는것이 더 나아보여서 massageRepository에서 새로 만든것같은데, 사용하지 않는 코드를 남겨두는것은 좋지않다고 생각합니다.
허나 사용중에 있다면 남겨두나, 사용하지 않는다면 지우는걸 권장 드립니다.

2022-06-03 06:58 UTC, qoxogus commented on src/main/java/com/server/Dotori/domain/massage/repository/MassageRepositoryImpl.java
> +    public List<MassageStudentsDto> findByMassageList() {
이 부분에 대해서 제가 답변 드리겠습니다.
아까 저와 이야기 나눈 후 추가된 쿼리라..

일단 명시적으로 join을 해주지 않아서 `member.createDate.asc`로 하게 된다면 
member를 from의 member로 처리하여
회원가입 할 때 Member Entity에 생성된 createDate순으로 정렬되게 됩니다.

또한 원래 Member의 안마의자 신청 상태만 APPLIED인 상태인 회원을 조회했지만
안마의자를 신청한 인원이 담긴 Entity(Massage Entity)를 기준으로 신청된 사람을 조회하는게 좋다고 생각하여
제가 제안했습니다.

2022-06-03 07:00 UTC, louis7308 commented on src/main/java/com/server/Dotori/domain/massage/repository/MassageRepositoryImpl.java
> +    public List<MassageStudentsDto> findByMassageList() {
원래 기존 findMemberByMassageStatus 에서 createDate.ase만 오름차순 으로 바꾸는 방식을 체택하였지만 Member Entity 부분에서 CreateDate 구문을 조회하기 때문에 자칫 Member가 생성한 날짜로 오해 할수 있어 따로 Massage 부분에서 생성된 시간을 기준으로 오름차순 정렬하는 방법을 선택했습니다.

2022-06-03 07:00 UTC, louis7308 commented on src/main/java/com/server/Dotori/domain/member/repository/member/MemberRepositoryImpl.java
> +        return queryFactory.from(member) // User   // user
이부분은 제가 확인하지 못했네요.. 수정하겠습니다!

2022-06-04 05:20 UTC, TeMlN commented on src/main/java/com/server/Dotori/domain/massage/repository/MassageRepositoryImpl.java
> +    public List<MassageStudentsDto> findByMassageList() {
아 그부분은 생각하지 못했어요. 답변 감사합니다!

2022-06-04 05:20 UTC, TeMlN approved these changes

2022-06-04 06:02 UTC, merged